dist: trusty

language: node_js
node_js:
- "8"


before_install:
- npm install @angular/cli
- npm install codecov -g
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
- npm install

script:
- npm run lint
- npm run build
- npm test -- --code-coverage


after_success:
- codecov