dist: trusty

language: node_js
node_js:
- "8"


before_install:
- npm install @angular/cli
- npm install codecov -g

install:
- npm install

script:
- npm run lint
- npm run build
- npm test -- --code-coverage


after_success:
- codecov